### PR TITLE
fix!: java options via env variable, to ensure they are enforced, even if tools would not pass on / respect java arguments

### PR DESCRIPTION
**Pull request by SilasK**
https://github.com/snakemake/snakemake-wrappers/pull/1322#issuecomment-1804157349

### CODE REVIEW

**Comment by dlaehnemann** [comment]
I think we should mark this as a breaking change, as this might break in some contexts / require updating the usage of the respective function. Not sure how exactly, but...

To add some context to the above link: Basically `BBTools` are implemented in Java, with `Bash` script wrappers around the different tools. And these wrappers don't pass Java options on to Java, but do complain about unknown arguments if you try to specify anything apart from `-Xmx`... *sigh*

But in addition, this seems like a more generic solution, IF it plays nicely with python setting the environment variables and then running the `shell()` commands.

**Review by dlaehnemann — CHANGES_REQUESTED** [review]
Hey @SilasK! @johanneskoester had the idea to simply implement this change to using `os.environ["JDK_JAVA_OPTIONS"]` in the `bbtools` wrapper. That way, we don't unexpectedly break any of the other Java wrappers and don't rely on any implicit OS behaviours if we don't have to. So basically take the string that `get_java_opts()` returns and stick it into `os.environ["JDK_JAVA_OPTIONS"]` instead of appending it to the command that is run. Does this make sense?

**Comment by SilasK** [comment]
I agree with making a bbtools-specific change. However, I don't know if the tmp dir argument is needed. I would rather not set the tmp dir.

**Comment by dlaehnemann** [comment]
But this is something that the user might want to set via snakemake command-line options or via the `resources: tempdir=` directive in a rule using the wrapper, so it would then be good if the wrapper did pass this on to the actual execution of the tool.

**Pull request closed without merging**
